### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by Philosoft** [tomverran/robots#2]
use expression example from README.md isn't working:
```
use \tomverran\Robots\RobotsTxt;
```

because of that https://github.com/tomverran/robots/blob/master/composer.json#L23

```
    "autoload": {
        "psr-4": {
            "tomverran\\Robot\\": "src/Robot/"
        }
    }
```

differens here - in readme `Robots` in composer.json `Robot` (without s at the end).

I don't sure where this should be fixed, so I created this issue instead of PR

**Comment by tomverran** [comment]
Many thanks for reporting! Shall fix now
