### ISSUE TITLE
Path matching is limited to directory boundary

### ISSUE THREAD

**Issue by ranvis** [tomverran/robots#8]
According to the draft http://www.robotstxt.org/norobots-rfc.txt
or Google implementation https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt?hl=en
path matching is expected to be done with start-with match.
The current implementation looks like to be somewhat limited on slash character boundary, making it potentially ignore disallowed path.

**Comment by ranvis** [comment]
There were other updates there but for this, I've confirmed start-with matching work precisely on 8b5f9ae.
Thank you for all the hard work @tomverran!

**Comment by tomverran** [comment]
Great, thanks for confirming that. I'm happy with these changes too so I'm going to go ahead and release 1.1
